# Generated by Django 4.1.1 on 2022-09-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.URLField(default='https://res.cloudinary.com/aaf-proj3/image/upload/v1663161208/360_F_376408140_kiazgwOvkEy0e50oxgF5kllIl7j2q1SQ_znlmvm.jpg', max_length=500),
        ),
    ]
