# Generated by Django 4.1.1 on 2022-09-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtypes', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='foodtype',
            field=models.ManyToManyField(related_name='recipes', to='foodtypes.foodtype'),
        ),
    ]
